/**
 * OpenClaw runtime manifest, local install markers and version compatibility.
 *
 * The shell declares the runtime version it was built and tested against in a
 * build-time manifest (`runtime-manifest.json`, generated by
 * scripts/pack-openclaw-runtime.mjs). Downloaded runtimes are stored per version
 * under `%LOCALAPPDATA%\grandpoem-studio\runtime\<version>` with an install
 * marker, and `runtime/current.json` points at the active one
 * (see paths.ts:getOpenClawDir).
 *
 * Why a manifest rather than reading the bundled runtime's package.json:
 * a download-mode build has no bundled runtime to read, and the *desired*
 * version must be knowable without the thing we are trying to fetch.
 *
 * Keep this module free of Electron-only APIs beyond what paths.ts already
 * wraps, so it stays unit-testable. Every filesystem helper takes an optional
 * `rootDir` so tests never touch the real user directory.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import {
  getOpenClawDir,
  getOpenClawDirSource,
  getRuntimeRootDir,
  isRuntimeDirUsable,
  type OpenClawDirSource,
} from './paths';
import { logger } from './logger';

export const RUNTIME_MANIFEST_FILE_NAME = 'runtime-manifest.json';
export const RUNTIME_REQUIRED_FILE_NAME = 'runtime-required.txt';
export const RUNTIME_INSTALL_MARKER_NAME = '.grandpoem-runtime.json';
export const RUNTIME_CONSENT_FILE_NAME = 'runtime-consent.json';
export const RUNTIME_INSTALL_MARKER_SCHEMA = 1;

/** Build-time description of the runtime this shell expects. */
export interface RuntimeManifest {
  schema: number;
  runtimeVersion: string;
  platform?: string;
  arch?: string;
  /** Remote archive. Absent for bundled-only builds. */
  archiveUrl?: string;
  sha256?: string;
  size?: number;
  fileCount?: number;
  /** Oldest shell version allowed to consume this runtime. */
  minShellVersion?: string;
  /** Reserved for a signed-manifest rollout. */
  signature?: string;
}

/** Written into `<runtime>/<version>/` once a runtime is fully in place. */
export interface RuntimeInstallMarker {
  schema: number;
  version: string;
  sha256?: string;
  size?: number;
  fileCount?: number;
  installedAt: string;
  source: 'download' | 'import' | 'bundled';
}

export type RuntimeReadinessReason = 'ok' | 'missing' | 'version-mismatch' | 'no-manifest';

export interface RuntimeReadiness {
  ready: boolean;
  reason: RuntimeReadinessReason;
  source: OpenClawDirSource;
  dir: string;
  installedVersion: string | null;
  desiredVersion: string | null;
  manifestPresent: boolean;
}

/**
 * Normalize a version string for comparison: trim whitespace (the NSIS helper
 * reads a one-line text file that may carry a trailing newline), drop a leading
 * `v`, and drop SemVer build metadata.
 */
export function normalizeRuntimeVersion(value: string | null | undefined): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim().replace(/^v/i, '');
  if (!trimmed) return null;
  return trimmed.split(/\s+/)[0].split('+')[0] || null;
}

/**
 * Parse JSON that may have been written by a Windows editor, which adds a
 * UTF-8 BOM that `JSON.parse` rejects.
 */
function parseJsonFile(filePath: string): unknown {
  return JSON.parse(readFileSync(filePath, 'utf-8').replace(/^\uFEFF/, ''));
}

/**
 * Whether an installed runtime satisfies the pin. Deliberately strict/exact for
 * now: the shell pins one runtime version. A compatibility range would need an
 * explicit `compatibleRange` field in the manifest first.
 */
export function isRuntimeVersionCompatible(
  installed: string | null | undefined,
  desired: string | null | undefined,
): boolean {
  const a = normalizeRuntimeVersion(installed);
  const b = normalizeRuntimeVersion(desired);
  if (!a || !b) return false;
  return a === b;
}

/** Candidate locations of the build-time manifest, most specific first. */
function runtimeManifestCandidates(): string[] {
  const candidates: string[] = [];
  const resourcesPath = (process as NodeJS.Process & { resourcesPath?: string }).resourcesPath;
  if (resourcesPath) {
    candidates.push(join(resourcesPath, RUNTIME_MANIFEST_FILE_NAME));
  }
  // Dev / unbundled: repo root (__dirname is electron/utils or dist-electron/main).
  candidates.push(join(__dirname, '..', '..', RUNTIME_MANIFEST_FILE_NAME));
  return candidates;
}

/** Read the build-time runtime manifest, or null when the build has none. */
export function readRuntimeManifest(): RuntimeManifest | null {
  for (const candidate of runtimeManifestCandidates()) {
    if (!existsSync(candidate)) continue;
    try {
      const parsed = parseJsonFile(candidate) as Partial<RuntimeManifest>;
      if (typeof parsed?.runtimeVersion !== 'string' || !parsed.runtimeVersion.trim()) {
        logger.warn(`[runtime] Manifest at ${candidate} has no runtimeVersion; ignoring.`);
        continue;
      }
      return {
        schema: typeof parsed.schema === 'number' ? parsed.schema : 1,
        runtimeVersion: parsed.runtimeVersion,
        platform: parsed.platform,
        arch: parsed.arch,
        archiveUrl: parsed.archiveUrl,
        sha256: parsed.sha256,
        size: parsed.size,
        fileCount: parsed.fileCount,
        minShellVersion: parsed.minShellVersion,
        signature: parsed.signature,
      };
    } catch (error) {
      logger.warn(`[runtime] Failed to parse runtime manifest at ${candidate}:`, error);
    }
  }
  return null;
}

/** The runtime version this shell expects, or null when nothing is pinned. */
export function getDesiredRuntimeVersion(): string | null {
  return normalizeRuntimeVersion(readRuntimeManifest()?.runtimeVersion);
}

/** Read the `version` field of a runtime tree's package.json. */
export function readRuntimePackageVersion(dir: string): string | null {
  try {
    const pkg = parseJsonFile(join(dir, 'package.json')) as { version?: string };
    return normalizeRuntimeVersion(pkg?.version);
  } catch {
    return null;
  }
}

export function getRuntimeVersionDir(
  version: string,
  rootDir: string = getRuntimeRootDir(),
): string {
  return join(rootDir, normalizeRuntimeVersion(version) ?? version);
}

export function getRuntimeInstallMarkerPath(
  version: string,
  rootDir: string = getRuntimeRootDir(),
): string {
  return join(getRuntimeVersionDir(version, rootDir), RUNTIME_INSTALL_MARKER_NAME);
}

export function readRuntimeInstallMarker(
  version: string,
  rootDir: string = getRuntimeRootDir(),
): RuntimeInstallMarker | null {
  try {
    const parsed = parseJsonFile(
      getRuntimeInstallMarkerPath(version, rootDir),
    ) as Partial<RuntimeInstallMarker>;
    if (typeof parsed?.version !== 'string' || !parsed.version) return null;
    return {
      schema: typeof parsed.schema === 'number' ? parsed.schema : RUNTIME_INSTALL_MARKER_SCHEMA,
      version: parsed.version,
      sha256: parsed.sha256,
      size: parsed.size,
      fileCount: parsed.fileCount,
      installedAt: typeof parsed.installedAt === 'string' ? parsed.installedAt : '',
      source: parsed.source ?? 'download',
    };
  } catch {
    return null;
  }
}

export function writeRuntimeInstallMarker(
  version: string,
  marker: Omit<RuntimeInstallMarker, 'schema'> & { schema?: number },
  rootDir: string = getRuntimeRootDir(),
): void {
  const dir = getRuntimeVersionDir(version, rootDir);
  mkdirSync(dir, { recursive: true });
  const payload: RuntimeInstallMarker = {
    schema: marker.schema ?? RUNTIME_INSTALL_MARKER_SCHEMA,
    version: normalizeRuntimeVersion(marker.version) ?? marker.version,
    sha256: marker.sha256,
    size: marker.size,
    fileCount: marker.fileCount,
    installedAt: marker.installedAt || new Date().toISOString(),
    source: marker.source,
  };
  writeFileSync(join(dir, RUNTIME_INSTALL_MARKER_NAME), JSON.stringify(payload, null, 2), 'utf-8');
}

/**
 * A version directory counts as installed only when it carries a valid marker
 * *and* still looks like a runtime tree — a half-extracted directory must never
 * be treated as usable.
 */
export function isRuntimeVersionInstalled(
  version: string,
  rootDir: string = getRuntimeRootDir(),
): boolean {
  const dir = getRuntimeVersionDir(version, rootDir);
  if (!existsSync(dir) || !isRuntimeDirUsable(dir)) return false;
  return readRuntimeInstallMarker(version, rootDir) !== null;
}

/** Versions present on disk, newest first (by marker timestamp, then mtime). */
export function listInstalledRuntimeVersions(rootDir: string = getRuntimeRootDir()): string[] {
  let entries: string[];
  try {
    entries = readdirSync(rootDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
      .map((entry) => entry.name);
  } catch {
    return [];
  }

  return entries
    .filter((name) => isRuntimeVersionInstalled(name, rootDir))
    .map((name) => {
      const marker = readRuntimeInstallMarker(name, rootDir);
      let mtime = 0;
      try {
        mtime = statSync(getRuntimeVersionDir(name, rootDir)).mtimeMs;
      } catch {
        // ignore
      }
      const installedAtMs = marker?.installedAt ? Date.parse(marker.installedAt) : Number.NaN;
      return { name, sortKey: Number.isFinite(installedAtMs) ? installedAtMs : mtime };
    })
    .sort((a, b) => b.sortKey - a.sortKey)
    .map((entry) => entry.name);
}

export function removeRuntimeVersion(
  version: string,
  rootDir: string = getRuntimeRootDir(),
): void {
  try {
    rmSync(getRuntimeVersionDir(version, rootDir), { recursive: true, force: true });
  } catch (error) {
    logger.warn(`[runtime] Failed to remove runtime version ${version}:`, error);
  }
}

/**
 * Keep the newest `keep` versions (plus `protect`), removing the rest.
 * Called after a successful switch so rollback stays possible without letting
 * the runtime directory grow without bound.
 */
export function pruneRuntimeVersions(
  keep: number,
  protect: string[] = [],
  rootDir: string = getRuntimeRootDir(),
): string[] {
  const protectedSet = new Set(
    protect.map((value) => normalizeRuntimeVersion(value) ?? value).filter(Boolean),
  );
  const versions = listInstalledRuntimeVersions(rootDir);
  const removable = versions.filter((version) => !protectedSet.has(version)).slice(Math.max(keep, 0));
  for (const version of removable) {
    removeRuntimeVersion(version, rootDir);
  }
  return removable;
}

export type RuntimeConsent = 'granted' | 'denied' | 'unset';

export interface RuntimeConsentRecord {
  consent: boolean;
  requestedAt?: string;
  desiredVersion?: string;
  source?: 'installer' | 'app';
}

/**
 * The consent file lives *next to* the runtime directory (i.e.
 * `%LOCALAPPDATA%\grandpoem-studio\runtime-consent.json`) so the NSIS installer
 * can write it before the app has ever created its runtime folder, and so the
 * app never asks a second time after the installer already did.
 */
export function getRuntimeConsentPath(rootDir: string = getRuntimeRootDir()): string {
  return join(dirname(rootDir), RUNTIME_CONSENT_FILE_NAME);
}

export function readRuntimeConsent(rootDir: string = getRuntimeRootDir()): RuntimeConsent {
  try {
    const parsed = parseJsonFile(getRuntimeConsentPath(rootDir)) as Partial<RuntimeConsentRecord>;
    if (parsed?.consent === true) return 'granted';
    if (parsed?.consent === false) return 'denied';
  } catch {
    // missing or unreadable -> user has not been asked yet
  }
  return 'unset';
}

export function writeRuntimeConsent(
  consent: boolean,
  extra: { desiredVersion?: string; source?: 'installer' | 'app' } = {},
  rootDir: string = getRuntimeRootDir(),
): void {
  const target = getRuntimeConsentPath(rootDir);
  mkdirSync(dirname(target), { recursive: true });
  const payload: RuntimeConsentRecord = {
    consent,
    requestedAt: new Date().toISOString(),
    desiredVersion: extra.desiredVersion,
    source: extra.source ?? 'app',
  };
  writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`, 'utf-8');
}

/** Resolve the runtime directory and report whether it satisfies the pin. */
export function getRuntimeReadiness(): RuntimeReadiness {
  const dir = getOpenClawDir();
  const source = getOpenClawDirSource();
  const manifest = readRuntimeManifest();
  const desiredVersion = normalizeRuntimeVersion(manifest?.runtimeVersion);
  const manifestPresent = manifest !== null;

  if (!isRuntimeDirUsable(dir)) {
    return {
      ready: false,
      reason: 'missing',
      source,
      dir,
      installedVersion: null,
      desiredVersion,
      manifestPresent,
    };
  }

  const installedVersion = readRuntimePackageVersion(dir);

  // No pin (dev, legacy builds) means nothing to enforce.
  if (!desiredVersion) {
    return {
      ready: true,
      reason: 'no-manifest',
      source,
      dir,
      installedVersion,
      desiredVersion: null,
      manifestPresent,
    };
  }

  if (isRuntimeVersionCompatible(installedVersion, desiredVersion)) {
    return {
      ready: true,
      reason: 'ok',
      source,
      dir,
      installedVersion,
      desiredVersion,
      manifestPresent,
    };
  }

  return {
    ready: false,
    reason: 'version-mismatch',
    source,
    dir,
    installedVersion,
    desiredVersion,
    manifestPresent,
  };
}
